title: Aberdeen Developers .Net User Group
description: ""
baseurl: ""
disqus_shortname: aberdeendevelopersnetusergroup
url: "http://www.aberdeendevelopers.co.uk"

images:           http://www.aberdeendevelopers.co.uk/images

# Owner/author information
owner:
  name:           Aberdeen Developers .Net User Group
  avatar:         
  bio:            
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        adnuguk
  github:         adnuguk
  linkedin:       Aberdeen-Developers-Net-User-Group-3846270

# Analytics and webmaster tools stuff goes here
google_analytics: UA-19680256-1   

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
